name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Code Style
        run: gofmt -l -s -d .

      - name: Run Tests
        run: go test ./...
